### ISSUE TITLE
Make is possible to place a square token instead of a circle

### ISSUE THREAD

**Issue by digitalsadhu** [otfbm/issues#15]
**Is your feature request related to a problem? Please describe.**
As the title says... do we want/need this? Why?

**Describe the solution you'd like**
Draw a square token

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lpduarte** [comment]
Using corners for the extra info we need to add to the tokens, so I'd vote `no` for this.

**Comment by mjs1** [comment]
I think who ever asked for this wants to use tokens for displaying something other than PC/NPCs.
Should find out what they're actually wanting to do.

**Comment by digitalsadhu** [comment]
Yea. I’m going to close this.
