### ISSUE TITLE
Overlays: how they appear outside the map

### ISSUE THREAD

**Issue by lpduarte** [otfbm/issues#18]
**Is your feature request related to a problem? Please describe.**
The way overlays appear outside the map.

**Describe the solution you'd like**
The map should work as a mask and not show any overlay beyond its edges, only if there's more map beyond it.

**Describe alternatives you've considered**
NA.

**Additional context**
![otfbm-overlay-test-3](https://user-images.githubusercontent.com/16154620/92031194-257fd780-ed60-11ea-80a6-e7cf797587c5.jpg)

**Comment by mjs1** [comment]
Setting the `e` option "Disable border opacity" will stop this from
happening.

I would have thought with transparency this information is useful? Any
tokens placed in the border will show up in the same way currently too.

**Comment by lpduarte** [comment]
I see what you're saying with `-mapoptions e` but what I want is for the top left overlay to never appear outside the map's border even if `-mapoptions e` isn't used.

**Comment by lpduarte** [comment]
Closed. Nice one.
