### ISSUE TITLE
List of token codes stored with user variables

### ISSUE THREAD

**Issue by JamesHurburgh** [otfbm/issues#20]
**Is your feature request related to a problem? Please describe.**
I need to keep a list of my PC's and NPC's token codes to paste into discord whenever I setup a new combat.

**Describe the solution you'd like**
Whenever someone joins initiative I want it to be able to look up from a list of stored tokens and assign one automatically if the name matches.

**Describe alternatives you've considered**
Alternatively, I want to be able to quickly type the following to load the token from a stored list:
!map -t Character1 -[loadtoken|lookuptoken|autotoken|findtoken]

**Additional context**
The tokens need to be managed somehow probably with something like:
!map -updatetoken <token> <name>
!map -removetoken <name>
!map -listtokens

**Comment by Croebh** [comment]
This is coming to a `!map` alias near you, very soon!
