### ISSUE TITLE
Common Token Reference Page

### ISSUE THREAD

**Issue by rougegoat** [otfbm/issues#21]
**Is your feature request related to a problem? Please describe.**
A common reference page for token images similar to !map -spellbook to help look up common enemy types like goblins, skeletons, ghouls, etc.

**Describe the solution you'd like**
Similar to !map -spellbook, you could bring up a pre-generated list of approved loaded common enemies.  Ideal commands for this would be !map -tokenlist, -tokenbook, or -bestiary.

**Describe alternatives you've considered**
Loading up individual tokens myself to generate their code or a website to list all the codes uploaded.  The former is going to lead to a lot of near identical images being uploaded.  The latter could lead to codes generated for copyrighted images being listed.  This general library of approved images would

**Comment by nerdsanddragons** [comment]
Feature !map tokenlist was added
