### ISSUE TITLE
Overlays: renaming -over line

### ISSUE THREAD

**Issue by lpduarte** [otfbm/issues#23]
**Is your feature request related to a problem? Please describe.**
This is both an issue for the map service and the alias. Currently adapting Rouge's Overlays Guide and I think the `-over line` command is a bit misleading. Since we've got walls and arrows, that are truly lines, the `-over line` command actually draws a quadrilateral shape, a rectangle in fact, well, sometimes a square, but there's a shortcut for that, but a rectangle nonetheless. It's true that users can set the length or width to 1px and make it a line centered on a coordinate but I bet the percentage of people doing that is quite small as it makes more sense to build a line on the grid, through `-wall`, than on the middle of a square.

**Describe the solution you'd like**
Renaming the `-over line` command to `-over rectangle` to make it more obvious and accurate.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mjs1** [comment]
the line overlay was made to represent spells like lightning bolt, which is 5ft wide: https://www.dndbeyond.com/spells/lightning-bolt

**Comment by lpduarte** [comment]
It does say line in the spell. But when you allow the user to set both the width and the length he'll probably use it for more than just 5ft lines, making the name misleading. I'm looking at this from a UX PoV and I see 2 possible solutions:
1. create a new command to only allow `<length>`,`<start>`, and `<end>`, and it's locked at 5ft wide, called `line`, and changing the current command's name to `area` or `rectangle`;
2. or keep it as is :)

**Comment by Croebh** [comment]
Think I'll opt for keeping it as it is for now, may revisit this in the future.
