### ISSUE TITLE
Wall color

### ISSUE THREAD

**Issue by williamtstanley** [otfbm/issues#24]
**Is your feature request related to a problem? Please describe.**
With dark backgrounds it can be hard to see the walls

**Describe the solution you'd like**
A command to change the wall color to a hex code or similar would be great. `!map -wallcolor #FFFFFF`
![Screen Shot 2020-09-14 at 9 55 12 AM](https://user-images.githubusercontent.com/12862939/93115327-8ec0ee00-f670-11ea-972b-782ba7385867.png)

**Comment by digitalsadhu** [comment]
@mjs1 has begun work on this

**Comment by digitalsadhu** [comment]
Done in https://github.com/otfbm/maps/pull/37
Use `-c` to specify colors eg. `https://otfbm.io/_-crB2G2G4H4-dH6G6G8-sF9E10-bC10B10B2_-cbB6-oG6`
