### ISSUE TITLE
Loading initial map from otfbm url

### ISSUE THREAD

**Issue by williamtstanley** [otfbm/issues#25]
**Is your feature request related to a problem? Please describe.**
As a user I would  like to be able to load a pre-configured map from a otfbm url

**Describe the solution you'd like**
`!map -loadurl https://otfbm.io/20x15/_D3-oK3-dN7-bN13-sD13-oD11-dD7D3_F6J6-dJ9F9F6`

**Comment by digitalsadhu** [comment]
I’m super into this. Being able to set up the map in a browser tab and then just import the url would be handy for me.

**Comment by williamtstanley** [comment]
Ya my plan was to use the tool I made to generate maps quickly and then just save them to load into discord as needed

**Comment by nerdsanddragons** [comment]
Started working on this feature in the alias and just need to refine it. Currently I have it reading the url and adjusting the map size and applying the walls that were created. If we are wanting to also import additional things then getting that to work is going to take a while.

**Comment by williamtstanley** [comment]
I think at least for my use adding walls is enough. I could see an argument for objects though. Not sure how Tokens would work with the init system so I would probably say skip those.

**Comment by nerdsanddragons** [comment]
Objects shouldn't be hard but combatants I'm incorporating in a new feature -savebattle and -loadbattle. So if someone sets up the actual map- mapbg, mapsize, mapoptions, walls and objects I can make that work.

**Comment by digitalsadhu** [comment]
Do we still need this now that we have a way to load map state from a config file?
See http://docs.otfbm.com/#/predefined-maps-and-tokens

**Comment by williamtstanley** [comment]
My main use case was to use it in tandem with the draw tool. I could update that to output/save json instead. 🤔

**Comment by nerdsanddragons** [comment]
We decided to pursue -json feature in the alias instead of -loadurl so closing out this pr.
