### ISSUE TITLE
Add shortened forms of all commands beginning with -map, e.g. -attach, -size, -view, -options, -bg, etc.

### ISSUE THREAD

**Issue by BardicPerspiration** [otfbm/issues#27]
Suggestion: Add shortened forms of all commands beginning with -map, e.g. -attach, -size, -view, -options, -bg, etc.

I can't read or type the word "map" anymore.

**Comment by Croebh** [comment]
Biggest issue is `-size`, which is already used for setting the size of a token

**Comment by Croebh** [comment]
I added `-options`, `-attach`, `-view`, `-bg` in the new build (coming out soon)

**Comment by BardicPerspiration** [comment]
Sounds good, thanks!
