### ISSUE TITLE
Add tracking query parameters to URL

### ISSUE THREAD

**Issue by digitalsadhu** [otfbm/issues#30]
**Is your feature request related to a problem? Please describe.**
I would like to be able to generate metrics about whether a request is coming from the alias vs direct URL input. I would also like to be able to generate metrics about requests that come from the testing alias vs that which is used in production by the general ppl.

**Describe the solution you'd like**

2 things: 

1. Add `&d=1` when the alias is in dev mode. 
2. Always add `&a=1`.

**Comment by Croebh** [comment]
Donezo

https://github.com/Croebh/Avrae-Customizations/commit/a1838eecf8952b64d89c84ede26b3083a8f00f73

**Comment by digitalsadhu** [comment]
Note to self: ;)

`?a=1&cid={ctx.channel.id}&sid={ctx.guild.id}&uid={ctx.author.id}{"&d=1" if testVersion else ""}
a, cid, sid, uid, d`
