### ISSUE TITLE
Changes to !map help dm

### ISSUE THREAD

**Issue by lpduarte** [otfbm/issues#31]
Adding z to the command as, according to Blob, zoom needs a "z" before the number now. Also changed the text to better explain what happens when the command is run.

```python
-desc "z<#> - Changes the map's resolution, range 1-3, accepts fractions. The higher the value the larger the map will be, allowing to zoom in without loosing image quality. Example: -options z1.5"
```

And further down that help page:

```python
-desc "You can set multiple settings at a time. Example: -options z2n would set the resolution at 2x and hide the grid."
```

**Comment by lpduarte** [comment]
Edited the second line so that it doesn't mention z having to be set first.

**Comment by nerdsanddragons** [comment]
This has been added
