### ISSUE TITLE
No way to turn off face recognition when uploading token images

### ISSUE THREAD

**Issue by MommaGunn** [otfbm/issues#34]
**Severity**: 
Low (formatting issues, things that don't impact operation)

**Describe the bug**
When uploading token images via url through the `!map -tokenimport <url>` alias, the end result is cropped by facial recognition software with no option to keep the full sized image.

**To Reproduce**
1. Go to a discord server loaded with the Avrae bot.
2. Run alias: `!map -tokenimport https://i.imgur.com/OC0B0A8.png`
3. Copy resulting short code
3. Run full `!map` alias in active initiative
4. Assign token to character via the `!map -t <target> -loadtoken <short code copied earlier>`

**Expected behavior**
I expected the full token that I designed to load to the active map

**Screenshots**
![token_3](https://user-images.githubusercontent.com/72631493/95636027-11fd1600-0a5c-11eb-89f3-ce3ca2e07c92.png)

![Screenshot_2020-10-09-18-03-03-002_com discord](https://user-images.githubusercontent.com/72631493/95636048-1f1a0500-0a5c-11eb-923e-3fe8266f5765.jpg)

**Additional context**
The facial recognition feature is nice, but it would be better to have an option to upload the full image.

**Comment by digitalsadhu** [comment]
Great issue thanks @MommaGunn !

**Comment by digitalsadhu** [comment]
@MommaGunn 
Fixed in otfbm/maps#41
