### ISSUE TITLE
Remove legacy -attach command from Getting Started example

### ISSUE THREAD

**Issue by rougegoat** [otfbm/issues#35]
**Describe the bug**
When the "Getting Started" guide was initially written up, you still had to anchor the map manually to a combatant.  Now that `!map` will auto-attach to combatants named DM, Map, or Lair, I don't think it needs to be used in the beginner focused guide.

**To Reproduce**
Documentation change.  End of Getting Started -> Section 2.

> Sweet. So now we have the map anchored to the initiative order through a specific combatant, set to a good size, and with a custom background. That’s a lot of commands to run separately. Luckily, you can use all those arguments on the same command instead:

> > !map -attach DM -mapsize 26x14 -bg https://i.imgur.com/WnTUKcJ.jpg

**Expected behavior**
Rephrase to something like

> Sweet.  Now that we have our custom background and the grid set to a good size, we can start adding creatures, objects, overlays, and other things to it.  You can also run these and other commands in one line instead of separately.  That would look like this:

> > !map -mapsize 26x14 -bg https://i.imgur.com/WnTUKcJ.jpg

**Comment by Ydomat** [comment]
Thanks! ill do this in my commit this week!

**Comment by Ydomat** [comment]
addressed with https://github.com/otfbm/docs/commit/c449efd7c15c9cbcab519402dc41e2b225c3aec6
