### ISSUE TITLE
Map help View gives Error

### ISSUE THREAD

**Issue by storytellermahkasad** [otfbm/issues#39]
**Severity**: 
Low

**Describe the bug**
Calling `!map help view` gives an Avrae error instead of just displaying the base help.

**To Reproduce**
1. Type command `!map help view`
2. See error

**Expected behavior**
Should show the default help, or perhaps DM help. Not error.

**Screenshots**
https://cdn.discordapp.com/attachments/712795723623694376/773616057247465502/unknown.png

**Comment by Croebh** [comment]
Fixed, though `view` doesn't have a specific help command :p
