### ISSUE TITLE
Tokens Documentation Needs Escape Character Added

### ISSUE THREAD

**Issue by rougegoat** [otfbm/issues#41]
**Describe the bug**
Tilda flags are not fully escaped in the Tokens documentation.
http://docs.otfbm.com/#/tokens

**To Reproduce**
Near the bottom in the example for disabling facial recognition, the example reads:

* with facial recognition /a2-satyr\~wcqj3/
* without facial recognition /a2-satyr~wcqj3~/

**Expected behavior**
It should read:

* with facial recognition /a2-satyr\~wcqj3/
* without facial recognition /a2-satyr\~wcqj3\~/

**Comment by nerdsanddragons** [comment]
Need to update object overlay info with new available objects...

    "Ladder": "$la",
    "Crowd": "$ow",
    "Stairs": "$st",
    "Thorns": "$or",
    "Statue Star": "$ss",
    "Magic Portal": "$mp",
    "Lightning": "$li",
    "Person": "$pe",
    "Trap": "$tr",
    "Trip WIre": "$tw",
    "Gargoyle Statue": "$gs",
    "Spiked Pit": "$sp",
    "Column": "$co",
    "Open Pit": "$po",
    "Stone Throne": "$th",
    "Fire": "$fi",
    "Crystals": "$cr",
    "Round Pillar": "$pr",
    "Brick Wall": "$bw",
    "Wind": "$wn",
    "Web": "$we",
    "Explosion": "$ex",
    "Covered Pit": "$pc",
    "Palisade": "$pa",
    "Spiked Trunk": "$un",
    "Secret Door": "$sd",
    "Square Pillar": "$ps",
    "Chair": "$ch",
    "Table": "$ta",
    "Net": "$ne",
    "Puddle": "$pu",
    "Chest": "$es"

**Comment by Ydomat** [comment]
addressed with https://github.com/otfbm/docs/commit/f57c13287733cd8c31a1df5ff92b2a817c210247

**Comment by Ydomat** [comment]
closing complete.
