### ISSUE TITLE
Allow the Multi-assign to Handle Saved Token Names

### ISSUE THREAD

**Issue by storytellermahkasad** [otfbm/issues#46]
**Is your feature request related to a problem? Please describe.**
When using the mass editing format `-t <target>|[location]|[size]|[color]|[token]|[height]` it would be nice if the token value handled saved token names.

**Describe the solution you'd like**
The check for token would look at savedtokens first and then default to shortcode if no match was found.

**Describe alternatives you've considered**

**Additional context**

**Comment by nerdsanddragons** [comment]
Feature Request has been added to map alias
