### ISSUE TITLE
Map options subtraction error

### ISSUE THREAD

**Issue by WhisperGhost** [otfbm/issues#56]
**Severity**: 
 High (a broken feature)

**Describe the bug**
When using the (-) option when removing items from the options of the map it resets all options.

**To Reproduce**
1. add options to map: -options c70d
2. remove one option: -options -c70 
3. map options reset

**Expected behavior**
only the option after (-) should me removed 

**Screenshots**
![error 2](https://user-images.githubusercontent.com/115854223/195965955-1069f11a-8283-456e-bbf8-b7c60a68304d.png)
![error 1](https://user-images.githubusercontent.com/115854223/195965956-a196288c-f997-4def-ae17-b513788d16d4.png)

**Comment by digitalsadhu** [comment]
This sounds like something with the Alias rather than the underlying map service. Thoughts @Croebh @nerdsanddragons ?

**Comment by Croebh** [comment]
Definitely an alias issue, I'll take a look

**Comment by Croebh** [comment]
Should be fixed!
